### ISSUE TITLE
autolaunch

### ISSUE THREAD

**Issue by hamid07ss** [i-Naji/tabchi#2]
سلام دوستان.
دستور

> ./bot autolaunch

وقتی تعداد ربات ها بیشتر از 10 تا شد دیگه کار نکرد.
درواقع کار میکنه ولی فقط سری اول...یعنی این دستور رو میزنم ربات ها همه اجرا میشن منتهی 20 دقیقه دیگه دوباره ربات ها رو اجرا نمیکنه. و همین باعث میشه که ربات ها 
restart
نشن و بیش از حد از رم سرور استفاده کنن

قبل از اینکه ربات ها از 10 تا بیشتر بشه این دستور در لیست پردازش های درحال اجرا نشون داده میشد ولی وقتی از ده تا بیشتر شد دیه نشون داده نمیشه انگار باز نمیمونه و به جاش این دستور نشون داده میشه:

> tmux new-session -d -s bot-10 ./bot 10

درحالی که تعداد ربات های من بیشتر از 10 هستش...
و شروع ربات ها هم که 1 هستش
نمیدونم چرا این دستور رو نشون میده

![bots_issue](https://cloud.githubusercontent.com/assets/17006865/26110749/76da05e6-3a68-11e7-9a12-0d6030909f7c.PNG)

قبلا تو این لیست این دستور بود منتهی الان نیس..دلیلش چیه؟

> ./bot autolaunch

**Comment by naserrudini** [comment]
شما؟
در ۱۶ مهٔ ۲۰۱۷ ۱۸:۵۰، "hamid07ss" <notifications@github.com> نوشت:

**Comment by i-Naji** [comment]
از این دستور استفاده کنید

**Comment by i-Naji** [comment]
از این دستور استفاده کنید.
tmux new-session -s autolaunch "bash bot autolaunch"
